title: dsa

#links:
#     header:
#       - title: GitHub
#         url: https://github.com/kjetilthogersen
#    footer:
#      - title: GitHub
#        url: https://github.com/kjetilthogersen

ui:
    header:
        color1: "#1a97ab"
        color2: "#2f3b3d"
        trianglify: true

#social:
#    github:
#        user: kjetilthogersen
#        repo: kjetilthogersen.github.io
#    twitter:
#        enabled: false
#        via:
#        hash:
#        account:
#    facebook:
#        enabled: false
#        profileUrl: