# Dependencies
#markdown:         kramdown
kramdown:
  math_engine: katex
#highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Kjetil Thøgersen
tagline:          '...'
description:      'Researcher, University of Oslo'
url:              ...
baseurl:          /

author:
  name:           'Kjetil Thøgersen'
  url:            ...

paginate:         5



plugins:
  - jemoji
